'use client';
import { useEffect,useState } from 'react';
import { Check,Heart,ImagePlus,LoaderCircle,Save,Sparkles } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { getSupabaseBrowser } from '@/lib/supabase-browser';

type Content=Record<string,string|null>; type Surprise={id?:string;position:number;label:string;title:string;description:string;locked:boolean;unlock_at?:string|null};
export default function AdminPortal(){const[authenticated,setAuthenticated]=useState(false);const[content,setContent]=useState<Content|null>(null);const[surprises,setSurprises]=useState<Surprise[]>([]);const[saving,setSaving]=useState(false);const[saved,setSaved]=useState(false);const[loading,setLoading]=useState(true);const[loadError,setLoadError]=useState('');const[error,setError]=useState('');
  async function load(){setLoading(true);setLoadError('');try{const accessResponse=await fetch('/api/access');if(!accessResponse.ok)throw new Error('No se pudo comprobar el acceso. Revisa las variables de Vercel.');const access=await accessResponse.json();setAuthenticated(Boolean(access.authenticated));if(access.authenticated){const response=await fetch('/api/content');const data=await response.json();if(!response.ok||!data.content){const d=data.diagnostic;const runtime=d?`\n\nDiagnóstico de Vercel:\n• Proyecto: ${d.projectRef}\n• Tipo de clave servidor: ${d.keyType}\n• Longitud: ${d.keyLength}\n• Espacios externos: ${d.hasOuterWhitespace?'sí':'no'}`:'';throw new Error(`${data.detail||data.error||'Supabase no ha podido cargar el contenido.'}${runtime}`);}setContent(data.content);setSurprises(data.surprises||[]);}}catch(cause){setLoadError(cause instanceof Error?cause.message:'No se pudo cargar el portal.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function unlock(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const r=await fetch('/api/access',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({date:d.get('date')})});if(!r.ok){setError('Esa no es nuestra fecha.');return;}setAuthenticated(true);await load();}
  function field(key:string,value:string){setContent(c=>({...c,[key]:value}));}
  async function uploadHero(file?:File){if(!file||!content)return;setSaving(true);try{const ticket=await fetch('/api/uploads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:file.name,type:file.type,size:file.size})}).then(r=>r.json());const{error}=await getSupabaseBrowser().storage.from('memories').uploadToSignedUrl(ticket.path,ticket.token,file,{contentType:file.type});if(error)throw error;setContent({...content,hero_media_path:ticket.path,hero_media_url:URL.createObjectURL(file)});}finally{setSaving(false);}}
  async function save(){if(!content)return;setSaving(true);setSaved(false);const r=await fetch('/api/content',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({content,surprises})});setSaving(false);if(r.ok){setSaved(true);setTimeout(()=>setSaved(false),1800);}else setError('No se pudieron guardar los cambios.');}
  if(loading)return <main className="admin-loading"><div><LoaderCircle/><span>Preparando vuestro portal…</span></div></main>;
  if(loadError)return <main className="admin-error"><div><span>Algo falta por conectar</span><h1>El portal no puede cargar todavía</h1><p>{loadError}</p><button onClick={()=>void load()}>Volver a intentar</button><a href="/">Volver a la web</a></div></main>;
  if(!authenticated)return <main className="admin-login"><div><span><Heart fill="currentColor"/></span><p>Portal privado</p><h1>Nuestra fecha abre la puerta</h1><form onSubmit={unlock}><Input name="date" type="date" required/><button>Entrar</button>{error&&<small>{error}</small>}</form></div></main>;
  if(!content)return null;
  const textFields=[['hero_eyebrow','Texto superior'],['hero_pretitle','Dedicatoria corta'],['hero_title','Título'],['hero_name','Nombre'],['hero_description','Texto principal'],['story_kicker','Etiqueta de la historia'],['story_title','Título de la historia'],['story_description','Descripción de la historia'],['love_note','Carta de amor'],['footer_text','Texto final']];
  return <main className="admin-page"><header><div><span>MJ</span><div><small>Portal privado</small><h1>Todo vuestro universo, en tus manos</h1></div></div><a href="/">Ver la web</a></header><section className="admin-shell"><aside><a href="#portada">Portada y textos</a><a href="#sorpresas">Sorpresas</a><a href="/#recuerdos">Recuerdos</a></aside><div className="admin-content"><section id="portada"><p className="section-kicker">Contenido principal</p><h2>Portada y textos</h2><div className="admin-cover">{content.hero_media_url?<img src={content.hero_media_url} alt="Portada actual"/>:<span><ImagePlus/>Sin foto de portada</span>}<label>Cambiar portada<Input type="file" accept="image/*,video/*" onChange={e=>void uploadHero(e.target.files?.[0])}/></label></div><div className="admin-fields">{textFields.map(([key,label])=><label key={key}>{label}{key.includes('description')||key==='love_note'?<Textarea value={content[key]||''} onChange={e=>field(key,e.target.value)}/>:<Input value={content[key]||''} onChange={e=>field(key,e.target.value)}/>}</label>)}</div></section><section id="sorpresas"><p className="section-kicker">El rincón secreto</p><h2>Sorpresas</h2><div className="admin-surprises">{surprises.map((s,i)=><article key={s.id||i}><Sparkles/><label>Etiqueta<Input value={s.label} onChange={e=>setSurprises(a=>a.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/></label><label>Título<Input value={s.title} onChange={e=>setSurprises(a=>a.map((x,n)=>n===i?{...x,title:e.target.value}:x))}/></label><label>Contenido<Textarea value={s.description} onChange={e=>setSurprises(a=>a.map((x,n)=>n===i?{...x,description:e.target.value}:x))}/></label><label className="admin-check"><input type="checkbox" checked={s.locked} onChange={e=>setSurprises(a=>a.map((x,n)=>n===i?{...x,locked:e.target.checked}:x))}/> Mantener bloqueada</label></article>)}</div></section></div></section><button className="admin-save" onClick={()=>void save()} disabled={saving}>{saving?<><LoaderCircle/>Guardando…</>:saved?<><Check/>Guardado</>:<><Save/>Guardar y publicar</>}</button></main>}
